### ISSUE TITLE
can't disable wired network

### ISSUE THREAD

**Issue by greenbamboo** [l300lvl/Network-Connections-Shortcut-Extension#2]
Hi,

thanks for this cool extension. I want to use it to activate the network when I need it and disable it when I don't. Unfortually I can't disable my wired network. It does work if I open the network manager and disable it there and it also works to activate it with you extension.

I am using Ubuntu 11.10.

Thanks for your time.

**Comment by l300lvl** [comment]
I'm not sure I understand the problem. This extension was designed to quickly open the Network Connections gui, and nothing more. From there you are able to edit/delete the connections, not enable/disable them. For that you should be able to use the menu itself, but this extension never claimed to enable or disable anything. You should file a bug report against Network Manager here, I believe Network Manager is also responsible for the gnome shell aspect, if not someone should forward your bug appropriatley: https://bugzilla.gnome.org/enter_bug.cgi?product=NetworkManager

**Comment by greenbamboo** [comment]
Oh, I see. Sorry my fault. Thanks for your quick anwser anyway!
