### ISSUE TITLE
"Support" for gnome-shell version 3.2.2.1

### ISSUE THREAD

**Issue by b-abadie** [l300lvl/Network-Connections-Shortcut-Extension#3]
Hi,
Please update line 35 of extension.js from
 if (current_version.length != 3
to
 if (current_version.length != 4
(or more) as gnome-shell version can be 3.2.2.1 for instance.

Bests,
Benjamin

**Comment by b-abadie** [comment]
Well, I wrote this too fast, there should be a <= test, or similar.
The test might be as well removed...

**Comment by l300lvl** [comment]
It already works for 3.2 and others. To install for those versions you should install from here https://extensions.gnome.org/extension/184/network-connections-shortcut/ It will automatically detect the correct version to install.

**Comment by b-abadie** [comment]
That's actually what I did.

**Comment by l300lvl** [comment]
If it installed correctly for 3.2/3.4 can you please close this bug?

If not, please report the errors you receive from looking glass in 3.2/3.4 by running Alt+F2 and r then enter.

**Comment by b-abadie** [comment]
I managed to get it work by changing the code.

In the unmodified version the message is "Strange version number (extension.js:35)." 
This is due to my version number : 3.2.2.1
I corrected by making this change : 

```
35c35
<     if (current_version.length != 3 || current_version[0] != 3) throw new Error("Strange version number (extension.js:35).");
---
>     if (current_version[0] != 3) throw new Error("Strange version number (extension.js:35).);
```

After correcting that I also had another error message : something like "undefined metadata.uuid" or similar (I can't c/c from the looking glass..)

I corrected by making this change : 

```
33c33
< function init() {
---
> function init(metadata) {
```

I think you have all the elements to identify the problem, let me know if not.

**Comment by l300lvl** [comment]
Glad you got it working, but since this is 3.2.2.1 specific I think what I will do is disable the switching in the 3.2 version on e.g.o so the site will force the older 3.2 version. 

It makes no sense why it sees 3.2.2.1 as a weird version, but I will look into it.

**Comment by b-abadie** [comment]
Actually it does make sense : you are splitting the version number into an array and checking if this array contains 3 elements. But with 3.2.2.1 the array contains... 4 elements!

As for the "Metadata", I believe this is indeed GS version-specific...

**Comment by l300lvl** [comment]
in the works for all versions from here on out and I may split everything up eventually, for now closing this, thanks again for the help!
